### PR TITLE
Fix readme, and add correct snake

### PR DESCRIPTION
**Pull request by notAperson535**
Fixed readme errors, and added a snake game to your account.

### CODE REVIEW

**Review by YanMaker — APPROVED** [review]

**Comment by YanMaker** [comment]
Thanks for the help!

**Comment by notAperson535** [comment]
@YanMaker snake should work in 6 hours

**Comment by YanMaker** [comment]
@notAperson535 It still won't work

snake

**Comment by notAperson535** [comment]
@YanMaker accept the new Pull Request

**Comment by YanMaker** [comment]
@notAperson535 I don't see it.

**Comment by YanMaker** [comment]
There aren't any open.

**Comment by notAperson535** [comment]
@YanMaker just opened it

**Comment by YanMaker** [comment]
Thanks.

**Comment by notAperson535** [comment]
I just left a note on the other PR (pull request)

**Pull request merged**
